import React from 'react';
import { shallow } from 'enzyme';
import * as Icons from './index';

test('Icons', () => {
  const icons = [
    Icons.Add,
    Icons.Address,
    Icons.ArrowDown,
    Icons.Close,
    Icons.Check,
    Icons.Add,
    Icons.Back,
    Icons.Block,
    Icons.Burger,
    Icons.Check,
    Icons.CheckCircle,
    Icons.Cli,
    Icons.Contract,
    Icons.ContractAbi,
    Icons.ContractExecute1,
    Icons.ContractExecute2,
    Icons.ContractExecute3,
    Icons.Copy,
    Icons.Dashboard,
    Icons.Download,
    Icons.Exit,
    Icons.Export,
    Icons.File,
    Icons.FullScreen,
    Icons.HardwareWallet,
    Icons.Home,
    Icons.Import,
    Icons.Method1,
    Icons.Method2,
    Icons.Method3,
    Icons.Method4,
    Icons.MultiSigWallet,
    Icons.Network,
    Icons.NetworkOk,
    Icons.NetworkDisconnected,
    Icons.Play,
    Icons.Print,
    Icons.QrCode,
    Icons.Remove,
    Icons.Search,
    Icons.Spinner1,
    Icons.Spinner2,
    Icons.Time,
    Icons.Token1,
    Icons.Token2,
    Icons.Token3,
    Icons.Windowed,
  ];
  icons.forEach(i => expect(shallow(React.createElement(i))).toBeDefined());
});
